version: "2"

# golangci-lint configuration

run:
  timeout: 5m
  tests: true

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/ginsys/shelly-manager

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

  disable:
    - depguard
    - funlen
    - gochecknoglobals
    - godot
    - godox
    - err113
    - mnd
    - nestif
    - testpackage
    - wsl

  settings:
    govet:
      enable:
        - shadow
    
    misspell:
      locale: US

issues:
  max-issues-per-linter: 0
  max-same-issues: 0