# golangci-lint configuration

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused
    - whitespace

  disable:
    - depguard
    - funlen
    - gochecknoglobals
    - godot
    - godox
    - err113
    - mnd
    - nestif
    - testpackage
    - wsl

linters-settings:
  goimports:
    local-prefixes: github.com/ginsys/shelly-manager
  
  govet:
    enable:
      - shadow
  
  misspell:
    locale: US

issues:
  exclude-dirs:
    - vendor
    - bin
    - data
    - web
    - docs
  exclude-files:
    - ".*_test.go"
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
    
    - path: internal/testutil/
      linters:
        - gosec
    
    - path: cmd/
      linters:
        - gocyclo
    
    - linters:
        - lll
      source: "^//go:generate "
  
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false