apiVersion: v1
kind: ConfigMap
metadata:
  name: shelly-manager-config
  namespace: default
  labels:
    app: shelly-manager
data:
  shelly-manager.yaml: |
    server:
      port: 8080
      host: 0.0.0.0
      log_level: "info"

    logging:
      level: "info"
      format: "json"
      output: "stdout"

    database:
      path: "/data/shelly.db"

    discovery:
      enabled: true
      networks:
        - 192.168.1.0/24
      interval: 300
      timeout: 5
      enable_mdns: true
      enable_ssdp: true
      concurrent_scans: 10

    dhcp:
      enabled: false
      # network: 192.168.1.0/24
      # start_ip: 192.168.1.100
      # end_ip: 192.168.1.200

    # opnsense:
    #   enabled: false
    #   host: 192.168.1.1
    #   username: admin
    #   password_file: /etc/secrets/opnsense-password

    metrics:
      enabled: true
      port: 9090
      path: /metrics
---
apiVersion: v1
kind: Secret
metadata:
  name: shelly-manager-secrets
  namespace: default
  labels:
    app: shelly-manager
type: Opaque
data:
  # Example: opnsense-password: <base64-encoded-password>
  # Use: echo -n 'your-password' | base64
  placeholder: cGxhY2Vob2xkZXI=