name: Bug Report
description: Report a bug in Shelly Manager
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the issue.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Shelly Manager Version
      placeholder: e.g. v0.5.5-alpha or commit hash
    validations:
      required: true
