apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: shelly-manager-development

resources:
- ../../base

namePrefix: dev-
namespace: shelly-dev

commonLabels:
  environment: development
  
patchesStrategicMerge:
- configmap-dev.yaml
- ingress-dev.yaml

configMapGenerator:
- name: shelly-manager-config
  behavior: merge
  literals:
  - LOG_LEVEL=debug
  - GIN_MODE=debug
  - DATABASE_PATH=/tmp/shelly.db
  - METRICS_ENABLE_DETAILED_TIMING=true

images:
- name: ghcr.io/ginsys/shelly-manager
  newTag: latest
- name: ghcr.io/ginsys/shelly-provisioner
  newTag: latest

replicas:
- name: shelly-manager
  count: 1