apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shelly-manager-data
  labels:
    app: shelly-manager
    component: storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: ""  # Use default storage class