# Development overrides
services:
  shelly-manager:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.manager
    environment:
      - SHELLY_LOGGING_LEVEL=debug
      - SHELLY_LOGGING_FORMAT=text
      - GIN_MODE=debug
      # Security & Export (optional for local development)
      - SHELLY_SECURITY_ADMIN_API_KEY=${ADMIN_API_KEY:-}
      - SHELLY_EXPORT_OUTPUT_DIRECTORY=${EXPORT_OUTPUT_DIR:-}
    ports:
      - "8080:8080"
      - "9090:9090"  # Prometheus metrics
    volumes:
      # Add hot-reload volumes for development
      - ../../web:/app/web:ro
      - ../../configs:/app/configs:ro

  shelly-provisioner:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.provisioner
    environment:
      - SHELLY_LOGGING_LEVEL=debug
      - SHELLY_LOGGING_FORMAT=text
      - GIN_MODE=debug
    volumes:
      - ../../configs:/app/configs:ro
